#!/bin/bash

# override properties like:
# export environment_music_scrobbling1_baseurl="http://localhost:"
export DYNAMO_ENDPOINT="http://localhost:${RESTDRIVER_PORT:="8081"}"
export AWS_HTTP_PROXY_HOST=""
export AWS_HTTP_PROXY_PORT=""
export AWS_ACCESS_KEY="dummykey"
export AWS_SECRET_KEY="dummysecret"
. test_helper.sh
TIMEOUT=30

if [ "$1" != "wait" ]
then
    run_test "onix.acceptance" $TIMEOUT
else
    lein ring server-headless
fi
